### ISSUE TITLE
Question regarding Dataset directory?

### ISSUE THREAD

**Issue by kasrahabib** [tobhey/NoRBERT#1]
Hi @tobhey,

I read the paper, great job!
Basically this is not an issue related to the models or any code provided in the project.
I have a question regarding the dataset directory available on this projects dataset.
Is it the whole dataset used for the project or just the split used for testing the models?

Thanks in advance!

**Comment by Gram21** [comment]
Hello @kasrahabib,

Thanks for your interest and kind words!

The datasets in this project are the complete datasets for training and testing. During the various runs, the dataset is split to represent the testing and training part accordingly.
In the Dataset folder, you can find the dataset for the classification of functional requirements in function, data, and behaviour. In the various folders within the Code directory, you can find the needed datasets (NFR dataset, relabeb promise, etc.) for each task.

I hope, I could help you!
