### ISSUE TITLE
Unable to load Pickle file

### ISSUE THREAD

**Issue by zeddmaxx** [tobhey/NoRBERT#2]
Hi, thanks for uploading the ipython notebooks! I had a query --  I'm unable to load the pickle file, I'm getting the error : UnpicklingError: NEWOBJ class argument isn't a type object

**Comment by tobhey** [comment]
Hej there,
Could you give us some more details on the notebook and where exactly you are getting this error?
Best regards

**Comment by zeddmaxx** [comment]
Hi, apologies, I got that running. I have another issue though --

I am trying to upgrade the notebooks to FastAI version 2.0 and specifically the: Task1_F_NFR_classification.ipynb and its predicting all the rows as 1. Do you have any idea how it could have happened? My code is present: https://colab.research.google.com/drive/1GHDCCZlAvliXq1c-M6V36l4yzsFx2TSl?usp=sharing

I did change the predictor class as follows: 
from torch import IntTensor
class Predictor:
    def __init__(self, classifier):
        self.classifier = classifier
        self.classes = [0, 1]

    def predict(self, text):
        prediction = self.classifier.predict(text)
        prediction_class = prediction[1]
        return IntTensor.item(np.argmax(prediction_class))

+ In the config I changed moms to -  moms=(0.8, 0.7, 0.01)

Any help is greatly appreciated!

**Comment by tobhey** [comment]
Hej, sorry for the late response...

We've looked into your adaptation, but couldn't find any issues ourselves. Thus, I have to admit that we cannot help you with this migration problem, sorry. We are still running it on FastAI 1...

Best regards
